import { createHash, createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';

const EPISODES=Array.from({length:11},(_,index)=>index+3);
const RULES={survived:['Survived Episode',1],teamReward:['Team Reward Win',1],teamImmunity:['Team Immunity Win',2],merge:['Made the Merge',3],finalist:['Final Tribal Council',5],winner:['Won the Season',8],reward:['Individual Reward Win',1],immunity:['Individual Immunity Win',2],idolFound:['Found Hidden Idol',1],idolPlay:['Successful Idol Play',3],advantage:['Successful Advantage',2],correctVote:['Correct Elimination Vote',1],zeroVotes:['Zero Elimination Votes',1],lostVote:['Lost Vote',-1],coinWin:['MrBeast Coin Flip Win',4],coinLoss:['Coin Flip Loss / Eliminated',-2],cry:['Cried',-1]};
const ROSTER=[['carter','Carter','jayz'],['linnea','Linnea','jayz'],['patt','Patt','jayz'],['devin','Devin','jayz'],['lewis','Lewis','josh'],['kristen','Kristen','josh'],['ori','Ori','josh'],['rob','Rob','josh'],['mike','Mike','biebelbogen'],['jelly','Jelly','biebelbogen'],['kliby','Kliby','biebelbogen'],['maggie','Maggie','biebelbogen'],['sharonda','Sharonda','nb'],['brady','Brady','nb'],['jenna','Jenna','nb'],['alexis','Alexis','nb']];
function initialState(){return {teams:[['jayz','JayZ'],['josh','Josh'],['biebelbogen','Biebelbogen'],['nb','NB']].map(([id,name])=>({id,name,passwordHash:null,priorRank:null})),contestants:ROSTER.map(([id,name,teamId])=>({id,name,teamId,status:'active',eliminatedEpisode:null,merge:false,finalist:false,winner:false})),episodes:EPISODES,events:[]};}
function env(){const url=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Missing Supabase environment variables.');return {url:url.replace(/\/$/,''),key,sessionSecret:process.env.LEAGUE_SESSION_SECRET||key};}
function send(res,status,body){res.setHeader('Cache-Control','no-store');res.status(status).json(body)}
function cookieValue(req,name){return (req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1)}
function sign(teamId,secret){const payload=Buffer.from(JSON.stringify({teamId,exp:Date.now()+1000*60*60*24*21})).toString('base64url');const signature=createHmac('sha256',secret).update(payload).digest('base64url');return payload+'.'+signature}
function session(req,secret){const value=cookieValue(req,'fs_session');if(!value)return null;const [payload,signature]=value.split('.');if(!payload||!signature)return null;const expected=createHmac('sha256',secret).update(payload).digest('base64url');if(signature.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return null;try{const data=JSON.parse(Buffer.from(payload,'base64url').toString());return data.exp>Date.now()?data.teamId:null}catch{return null}}
function setSession(res,teamId,secret){res.setHeader('Set-Cookie',`fs_session=${sign(teamId,secret)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=1814400`)}
function clearSession(res){res.setHeader('Set-Cookie','fs_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0')}
function hashPassword(password){const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('base64')}`}
function passwordMatches(password,stored){if(!stored)return false;const [salt,hash]=stored.split(':');const actual=scryptSync(password,salt,64).toString('base64');return actual.length===hash.length&&timingSafeEqual(Buffer.from(actual),Buffer.from(hash))}
async function rest(path,options={}){const {url,key}=env();const response=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=representation',...(options.headers||{})}});if(!response.ok)throw new Error('Unable to reach the league database.');return response.status===204?null:response.json()}
async function getState(){const records=await rest('league_state?select=state&id=eq.1');if(records[0]?.state)return records[0].state;const state=initialState();try{await rest('league_state',{method:'POST',body:JSON.stringify({id:1,state})})}catch{}const retry=await rest('league_state?select=state&id=eq.1');return retry[0]?.state||state}
async function writeState(state){await rest('league_state?id=eq.1',{method:'PATCH',body:JSON.stringify({state,updated_at:new Date().toISOString()})})}
function publicState(state){return {...state,teams:state.teams.map(({passwordHash,...team})=>team),episodes:EPISODES}}
function cleanName(name){return String(name||'').trim().replace(/\s+/g,' ').slice(0,32)}
function sanitizeAdminState(incoming,previous){
  const teamNames=new Set();const teams=previous.teams.map(team=>{const candidate=(incoming.teams||[]).find(item=>item.id===team.id)||team;const name=cleanName(candidate.name)||team.name;if(teamNames.has(name.toLowerCase()))throw new Error('Each team needs a unique name.');teamNames.add(name.toLowerCase());return {...team,name}});
  const contestants=previous.contestants.map(item=>{const candidate=(incoming.contestants||[]).find(value=>value.id===item.id)||item;return {...item,status:candidate.status==='eliminated'?'eliminated':'active',eliminatedEpisode:EPISODES.includes(+candidate.eliminatedEpisode)?+candidate.eliminatedEpisode:null,merge:Boolean(candidate.merge),finalist:Boolean(candidate.finalist),winner:Boolean(candidate.winner)}});
  const validContestants=new Set(contestants.map(item=>item.id)),seenCry=new Set(),seenMilestone=new Set();const events=[];
  for(const item of incoming.events||[]){if(!RULES[item.rule]||!validContestants.has(item.contestantId)||!EPISODES.includes(+item.episode))continue;const unique=`${item.rule}:${item.contestantId}:${item.episode}`,milestone=['merge','finalist','winner'].includes(item.rule)?`${item.rule}:${item.contestantId}`:'';if((item.rule==='cry'&&seenCry.has(unique))||(milestone&&seenMilestone.has(milestone)))continue;if(item.rule==='cry')seenCry.add(unique);if(milestone)seenMilestone.add(milestone);const [label,points]=RULES[item.rule];events.push({id:typeof item.id==='string'&&item.id.length<100?item.id:createHash('sha256').update(JSON.stringify(item)+Math.random()).digest('hex').slice(0,16),episode:+item.episode,contestantId:item.contestantId,rule:item.rule,label,points});}
  return {teams,contestants,episodes:EPISODES,events};
}
export default async function handler(req,res){
  try{const configuration=env();const action=req.method==='GET'?req.query.action:req.body?.action;const current=await getState();const teamId=session(req,configuration.sessionSecret);
    if(action==='state')return send(res,200,publicState(current));
    if(action==='session')return send(res,200,{teamId});
    if(action==='login'){const team=current.teams.find(item=>item.id===req.body.teamId);const secret=String(req.body.secret||'');if(!team||(!team.passwordHash&&secret!=='1234')||(team.passwordHash&&!passwordMatches(secret,team.passwordHash)))return send(res,401,{error:'That team name and password do not match.'});setSession(res,team.id,configuration.sessionSecret);return send(res,200,{teamId:team.id,needsSetup:!team.passwordHash});}
    if(action==='logout'){clearSession(res);return send(res,200,{ok:true});}
    if(!teamId)return send(res,401,{error:'Please sign in again.'});
    const team=current.teams.find(item=>item.id===teamId);if(!team)return send(res,401,{error:'Account not found.'});
    if(action==='setup'||action==='settings'){const name=cleanName(req.body.name);if(name.length<2)return send(res,400,{error:'Team name must have at least two characters.'});if(current.teams.some(item=>item.id!==teamId&&item.name.toLowerCase()===name.toLowerCase()))return send(res,400,{error:'That team name is already in use.'});const password=String(req.body.password||'');if(action==='setup'&&password.length<4)return send(res,400,{error:'Password must have at least four characters.'});team.name=name;if(password){if(password.length<4)return send(res,400,{error:'Password must have at least four characters.'});team.passwordHash=hashPassword(password)}await writeState(current);return send(res,200,{ok:true});}
    if(action==='adminSync'){if(teamId!=='jayz')return send(res,403,{error:'Administrator access required.'});const next=sanitizeAdminState(req.body.state||{},current);await writeState(next);return send(res,200,publicState(next));}
    return send(res,400,{error:'Unknown request.'});
  }catch(error){console.error(error);return send(res,500,{error:error.message||'League service unavailable.'})}
};
